### ISSUE TITLE
CIのpoetryインストールシェルを更新

### ISSUE THREAD

**Issue by sasano8** [sasano8/portfolio#2]
poetry 公式インストール手順の
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
が更新されているので横展開する。

```
- name: Install Poetry
        run: |
          # curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Load cached venv
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry install
```
